/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package traceunit.junit5

import io.opentelemetry.api.trace.SpanBuilder
import io.opentelemetry.api.trace.Tracer
import traceunit.junit5.span.MockedSpanBuilder

class TracerMock : Tracer {

    override fun spanBuilder(spanName: String): SpanBuilder {
        return MockedSpanBuilder()
    }
}
