/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package traceunit.junit5

import io.opentelemetry.api.trace.Tracer
import org.junit.jupiter.api.extension.ExtendWith
import traceunit.junit5.annotations.MockTracer

@ExtendWith(TraceunitExtension::class)
class LibraryTest {
    @MockTracer
    lateinit var tracer: Tracer

    @org.junit.jupiter.api.Test
    fun name() {
        println("Test")
    }
}
